spring.datasource.url=jdbc:mysql://${TIDB_HOST}:4000/locuspark?sslMode=VERIFY_IDENTITY
spring.datasource.username=${TIDB_USER}
spring.datasource.password=${TIDB_PASS}

# Ativa o Flyway especificamente para esta operação
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=false
spring.flyway.skip-executing-lock=true