spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
api.security.token.secret=${API_SECURITY_TOKEN_SECRET}

# Otimização do Pool do HikariCP para o ciclo de vida do Lambda (Estavam certas no seu arquivo!)
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=4000

# Desativa o Flyway no Lambda para evitar lentidão e problemas de concorrência
spring.flyway.enabled=false