spring.application.name=api
server.port=${PORT:8080}
spring.jpa.hibernate.ddl-auto=validate

spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

spring.config.import=optional:classpath:application-local.properties