ALTER TABLE clients
    ADD CONSTRAINT FK_CLIENTS_ON_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id);

ALTER TABLE users
DROP
COLUMN `role`;

ALTER TABLE users
    ADD `role` VARCHAR(255) NOT NULL;

ALTER TABLE companies
DROP
COLUMN status;

ALTER TABLE companies
    ADD status VARCHAR(255) NOT NULL;

ALTER TABLE clients
DROP
COLUMN type;

ALTER TABLE clients
    ADD type VARCHAR(255) NOT NULL;